language: node_js
node_js:
  - 14
  - 15
script:
  - npm i && npm run test:travis
services:
  - postgresql
addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
env:
  global:
    - PGUSER=postgres
    - PGDATABASE=todo
    - PGPORT=5432
before_script:
  - psql -c 'create database todo;' -U postgres
jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: '14'
      script: ./deploy.sh
