language: node_js
node_js:
  - 14
  - 15
script:
  - npm i && npm run test:travis
addons:
  postgresql: '13'
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/13/main/postgresql.conf
  - sudo pg_ctlcluster 13 main restart
before_script:
  - psql -c "CREATE DATABASE todo;" -U postgres
  - psql -c "CREATE USER todo-user WITH PASSWORD 'password123!';" -U postgres
services:
  - postgresql
jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: '14'
      script: ./deploy.sh
