version: '3.8'

services:
  api:
    build:
      context: ./api/
      target: development
    depends_on:
      - db
    environment:
      UV_THREADPOOL_SIZE: 128
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/usr/src/app
  db-migration:
    build:
      context: ./api/
      target: development
    command: npm run db:migration
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
      POSTGRES_DB: todo
    healthcheck:
      test: ['CMD', '/health-check.sh', 'todo', 'todo-user', 'password123!']
      interval: 15s
      timeout: 10s
      retries: 20
    ports:
      - '15432:5432'
    tty: true
    volumes:
      - ./api/db/health-check.sh:/health-check.sh
      - ./api/db/postgresql.conf:/etc/postgresql.conf
    tmpfs:
      - /var/lib/postgresql/data
