name: test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test-api:
    # Name the Job
    name: Lint and Test API
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Npm install
        run: pushd api && npm ci && npm run build && popd
      - name: Start docker environment for testing
        run: docker-compose up -d
      - name: Run tests
        run: pushd api && npm test && popd
      - name: Show docker compose logs
        run: docker-compose logs
        if: ${{ always() }}
      - name: Stop docker environment for testing
        run: docker-compose down
        if: ${{ always() }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true

  finish:
    needs: test-api
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
